System.getenv


package com.example.service;

import com.example.model.FailureDetails;
import com.example.model.FileDeletionRequest;
import com.example.model.AuditLog;
import com.example.mapper.AuditMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class AuditService {

    @Autowired
    private AuditMapper auditMapper;

    public void logAccessDenied(FileDeletionRequest request) {
        AuditLog auditLog = new AuditLog();
        auditLog.setSoeid(request.getSoeid());
        auditLog.setBusProcId(request.getBusProcId());
        auditLog.setAccessDenied(true);
        auditLog.setRequestPayload(request.toString());
        auditLog.setTimestamp(LocalDateTime.now());
        auditMapper.insertAuditLog(auditLog);
    }

    public void logDeletionAudit(FileDeletionRequest request, List<String> successFiles, List<FailureDetails> failureFiles) {
        String successFilesStr = String.join(",", successFiles);
        String failureFilesStr = failureFiles.stream()
            .map(f -> f.getFileName() + " (Error: " + f.getErrorMessage() + ")")
            .collect(Collectors.joining(","));

        AuditLog auditLog = new AuditLog();
        auditLog.setSoeid(request.getSoeid());
        auditLog.setFilePath(request.getFilePath());
        auditLog.setBusProcId(request.getBusProcId());
        auditLog.setSuccessFiles(successFilesStr);
        auditLog.setFailureFiles(failureFilesStr);
        auditLog.setRequestPayload(request.toString());
        auditLog.setTimestamp(LocalDateTime.now());

        auditMapper.insertAuditLog(auditLog);
    }
}


package com.example.model;

import java.util.List;

public class FileDeletionRequest {
    private String filePath;
    private List<String> fileDetails;
    private int busProcId;
    private String soeid;

    // Getters and Setters
    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public List<String> getFileDetails() {
        return fileDetails;
    }

    public void setFileDetails(List<String> fileDetails) {
        this.fileDetails = fileDetails;
    }

    public int getBusProcId() {
        return busProcId;
    }

    public void setBusProcId(int busProcId) {
        this.busProcId = busProcId;
    }

    public String getSoeid() {
        return soeid;
    }

    public void setSoeid(String soeid) {
        this.soeid = soeid;
    }
}



CREATE TABLE AUDIT_LOG (
    ID              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SOEID           VARCHAR2(50) NOT NULL,         -- User ID (SOEID)
    FILE_PATH       VARCHAR2(500) NOT NULL,        -- Directory path
    BUS_PROC_ID     NUMBER NOT NULL,               -- Business process ID
    SUCCESS_FILES   CLOB,                          -- Concatenated list of successfully deleted files
    FAILURE_FILES   CLOB,                          -- Concatenated list of failed files with error messages
    REQUEST_PAYLOAD CLOB,                          -- Full request payload in JSON format
    ACCESS_DENIED   CHAR(1) DEFAULT 'N',           -- Flag to denote access denial (Y or N)
    TIMESTAMP       TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Timestamp of when the request was processed
);

@RestController
@RequestMapping("/api/v1/files")
public class FileDeletionController {

    @Autowired
    private FileDeletionService fileDeletionService;

    @PostMapping("/delete")
    public ResponseEntity<?> deleteFiles(@RequestBody FileDeletionRequest request) {
        try {
            fileDeletionService.processDeletionRequest(request);
            return ResponseEntity.ok("Deletion request processed");
        } catch (AccessDeniedException e) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Access denied: " + e.getMessage());
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body("Error: " + e.getMessage());
        }
    }
}

